# Generated by Django 2.1.5 on 2019-10-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Class Name')),
            ],
        ),
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Classroom Name')),
                ('upVote', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=100, null=True, verbose_name='Location')),
                ('classroomImage', models.ImageField(null=True, upload_to='Images/%Y/%m/%d', verbose_name='Classroom Image')),
                ('course', models.ManyToManyField(related_name='classrooms', to='myClassrooms.Classes')),
            ],
        ),
    ]
