# Generated by Django 2.1.5 on 2019-11-14 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myClassrooms', '0002_auto_20191111_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='semester',
            field=models.CharField(default='', max_length=4, verbose_name='Semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='className',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myClassrooms.Classes', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='classroomName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myClassrooms.Classrooms', verbose_name='Classroom'),
        ),
    ]
