# Generated by Django 2.1.5 on 2019-11-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myClassrooms', '0003_auto_20191115_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='semester',
            field=models.CharField(max_length=5, verbose_name='Semester (eg. 1920A)'),
        ),
    ]
