# Generated by Django 2.1.5 on 2019-09-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Class Name')),
            ],
        ),
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Classroom Name')),
                ('upVote', models.IntegerField(null=True)),
                ('classroomImage', models.ImageField(upload_to='Images/%Y/%m/%d', verbose_name='Classroom Image')),
                ('course', models.ManyToManyField(to='myClassrooms.Classes')),
            ],
        ),
    ]
