# Generated by Django 2.1.5 on 2019-09-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myClassrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='Location'),
        ),
    ]
