# Generated by Django 2.1.5 on 2019-09-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myClassrooms', '0002_classrooms_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='classroomImage',
            field=models.ImageField(null=True, upload_to='Images/%Y/%m/%d', verbose_name='Classroom Image'),
        ),
    ]
