# Generated by Django 2.1.5 on 2019-09-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myClassrooms', '0003_auto_20190909_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='course',
            field=models.ManyToManyField(related_name='classrooms', to='myClassrooms.Classes'),
        ),
    ]
